/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { ClientBase, ApiException } from './clientex';
import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, from as _observableFrom, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class ActivityClient extends ClientBase {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        super();
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @return Success
     */
    test(): Observable<StringInfoModel> {
        let url_ = this.baseUrl + "/Api/Activity/Test";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return _observableFrom(this.transformOptions(options_)).pipe(_observableMergeMap(transformedOptions_ => {
            return this.http.request("post", url_, transformedOptions_);
        })).pipe(_observableMergeMap((response_: any) => {
            return this.transformResult(url_, response_, (r) => this.processTest(<any>r));
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.transformResult(url_, response_, (r) => this.processTest(<any>r));
                } catch (e) {
                    return <Observable<StringInfoModel>><any>_observableThrow(e);
                }
            } else
                return <Observable<StringInfoModel>><any>_observableThrow(response_);
        }));
    }

    protected processTest(response: HttpResponseBase): Observable<StringInfoModel> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <StringInfoModel>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<StringInfoModel>(<any>null);
    }
}

/** 模型 */
export interface StringInfoModel {
    data?: string | undefined;
    cacheKey?: string | undefined;
    isSuccess?: boolean | undefined;
    message?: string | undefined;
    code?: number | undefined;
}

/** 菜单结构 */
export interface NavBarItem {
    /** 图标 */
    icon?: string | undefined;
    url?: string | undefined;
    state?: number | undefined;
    name?: string | undefined;
    module?: string[] | undefined;
    selectedUrls?: string[] | undefined;
    children?: NavBarItem[] | undefined;
}

/** 模型 */
export interface NavBarItemListInfoModel {
    data?: NavBarItem[] | undefined;
    cacheKey?: string | undefined;
    isSuccess?: boolean | undefined;
    message?: string | undefined;
    code?: number | undefined;
}

/** 登录模型 */
export interface LoginModel {
    /** 是否登录0:非登录,1:登录 */
    isLogin?: number | undefined;
    /** 登录用户id */
    uId?: string | undefined;
    /** 登录人名字 */
    name?: string | undefined;
    /** debug描述 */
    remark?: string | undefined;
}

/** 模型 */
export interface LoginModelInfoModel {
    data?: LoginModel | undefined;
    cacheKey?: string | undefined;
    isSuccess?: boolean | undefined;
    message?: string | undefined;
    code?: number | undefined;
}

/** 登录参数 */
export interface ParamForLogin {
    /** 登录账号 */
    passId: string;
    /** 登录密码 */
    passWord: string;
    /** 验证码 */
    verCode: string;
}

export enum TypeScriptTemplate {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
}

export enum HttpClass {
    _0 = 0,
    _1 = 1,
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}